import type { Category, Product, ProductSource } from '@/domain/catalog/types'
import { InMemoryCatalogRepository } from '@/infrastructure/catalog/in-memory-catalog-repository'

const CHECKED_AT = '2026-09-10'

function officialSource(label: string, url: string): ProductSource {
  return { label, url, checkedAt: CHECKED_AT }
}

export const curatedCategories: Category[] = [
  { id: 'category:elektronica', slug: 'elektronica', name: 'Elektronica' },
  { id: 'category:wonen-huishouden', slug: 'wonen-huishouden', name: 'Wonen & huishouden' },
  { id: 'category:keuken-koffie', slug: 'keuken-koffie', name: 'Keuken & koffie' },
  { id: 'category:persoonlijke-verzorging', slug: 'persoonlijke-verzorging', name: 'Persoonlijke verzorging' },
  { id: 'category:sport-outdoor', slug: 'sport-outdoor', name: 'Sport & outdoor' },
  { id: 'category:tuin-klussen', slug: 'tuin-klussen', name: 'Tuin & klussen' },
]

export const curatedProducts: Product[] = [
  {
    id: 'curated:apple-macbook-air-13',
    slug: 'apple-macbook-air-13',
    title: 'Apple MacBook Air 13-inch (M5, 2026)',
    brand: 'Apple',
    mpn: 'MacBook Air 13-inch (M5)',
    description: 'De 13-inch MacBook Air uit 2026 met Apple M5-chip. Vergelijk vooral geheugen, opslag en GPU-uitvoering, omdat deze per configuratie kunnen verschillen.',
    categoryId: 'category:elektronica',
    visualKind: 'laptop',
    specifications: [
      { label: 'Chip', value: 'Apple M5' },
      { label: 'Display', value: '13,6-inch Liquid Retina · 2560 × 1664' },
      { label: 'Basisgeheugen', value: '16 GB centraal geheugen' },
      { label: 'Basisopslag', value: '512 GB SSD' },
      { label: 'Aansluitingen', value: 'MagSafe 3 · 2× Thunderbolt 4 · mini-jack' },
    ],
    source: officialSource('Apple Support', 'https://support.apple.com/nl-nl/126320'),
  },
  {
    id: 'curated:sony-wh-1000xm6',
    slug: 'sony-wh-1000xm6',
    title: 'Sony WH-1000XM6',
    brand: 'Sony',
    mpn: 'WH-1000XM6',
    description: 'Een draadloze over-ear hoofdtelefoon met actieve ruisonderdrukking. Let bij je keuze vooral op draagcomfort, accuduur en compatibiliteit met je apparaten.',
    categoryId: 'category:elektronica',
    visualKind: 'headphones',
    specifications: [
      { label: 'Gewicht', value: 'ca. 254 g' },
      { label: 'Accuduur', value: 'tot 30 uur met ruisonderdrukking' },
      { label: 'Bluetooth', value: 'Bluetooth 5.3' },
      { label: 'Snelladen', value: '3 min laden voor maximaal 3 uur gebruik' },
    ],
    source: officialSource('Sony Nederland', 'https://www.sony.nl/electronics/support/wireless-headphones-bluetooth-headphones/wh-1000xm6/specifications'),
  },
  {
    id: 'curated:samsung-galaxy-tab-s10-fe',
    slug: 'samsung-galaxy-tab-s10-fe',
    title: 'Samsung Galaxy Tab S10 FE Wi-Fi 128GB',
    brand: 'Samsung',
    mpn: 'SM-X520',
    description: 'Een 10,9-inch tablet voor media, studie en mobiel werken. Deze catalogusvariant is de Wi-Fi-uitvoering met 128 GB opslag.',
    categoryId: 'category:elektronica',
    visualKind: 'tablet',
    specifications: [
      { label: 'Display', value: '10,9-inch · 2304 × 1440 · tot 90 Hz' },
      { label: 'Opslag', value: '128 GB · microSD tot 2 TB' },
      { label: 'Batterij', value: '8000 mAh' },
      { label: 'Gewicht', value: 'ca. 497 g' },
      { label: 'Bescherming', value: 'IP68' },
    ],
    source: officialSource('Samsung Nederland', 'https://www.samsung.com/nl/tablets/galaxy-tab-s/galaxy-tab-s10-fe-gray-128gb-sm-x520nzaaeub/'),
  },
  {
    id: 'curated:logitech-mx-master-3s',
    slug: 'logitech-mx-master-3s',
    title: 'Logitech MX Master 3S',
    brand: 'Logitech',
    mpn: 'MX Master 3S',
    description: 'Een draadloze muis voor productiviteit en langdurig bureauwerk. Geschikt om tussen meerdere apparaten te wisselen via Bluetooth Low Energy of Logi Bolt.',
    categoryId: 'category:elektronica',
    visualKind: 'mouse',
    specifications: [
      { label: 'Sensor', value: 'tot 8000 DPI' },
      { label: 'Verbinding', value: 'Bluetooth Low Energy · Logi Bolt' },
      { label: 'Apparaten', value: 'koppeling met maximaal 3 apparaten' },
      { label: 'Opladen', value: 'USB-C' },
      { label: 'Scrollwiel', value: 'MagSpeed elektromagnetisch' },
    ],
    source: officialSource('Logitech', 'https://www.logitech.com/en-us/shop/p/mx-master-3s.910-006556'),
  },
  {
    id: 'curated:dyson-v12-detect-slim',
    slug: 'dyson-v12-detect-slim',
    title: 'Dyson V12 Detect Slim Absolute',
    brand: 'Dyson',
    mpn: 'V12 Detect Slim Absolute',
    description: 'Een snoerloze steelstofzuiger met een laag gewicht en verschillende vloerzuigmonden. Vergelijk vooral gebruiksduur, stofopvang en de meegeleverde accessoires.',
    categoryId: 'category:wonen-huishouden',
    visualKind: 'stick-vacuum',
    specifications: [
      { label: 'Zuigkracht', value: 'tot 150 Air Watt' },
      { label: 'Gebruiksduur', value: 'tot 60 minuten' },
      { label: 'Gewicht', value: 'ca. 2,2 kg' },
      { label: 'Stofreservoir', value: '0,35 l' },
      { label: 'Filtratie', value: '99,99% tot 0,3 micron volgens Dyson' },
    ],
    source: officialSource('Dyson Nederland', 'https://www.dyson.nl/stofzuigers/draadloos/v12/detect-slim-absolute-geel-nikkel'),
  },
  {
    id: 'curated:miele-complete-c3',
    slug: 'miele-complete-c3',
    title: 'Miele Complete C3 125 Edition',
    brand: 'Miele',
    gtin: '4002516743651',
    mpn: '12435960',
    description: 'Een sledestofzuiger met stofzak uit de Complete C3-serie. Deze catalogusvariant is de 125 Edition; accessoires kunnen per winkelbundel verschillen.',
    categoryId: 'category:wonen-huishouden',
    visualKind: 'canister-vacuum',
    specifications: [
      { label: 'Vermogen', value: '890 W' },
      { label: 'Stofzak', value: '4,5 l · HyClean Pure CO' },
      { label: 'Actieradius', value: '12 m' },
      { label: 'Gewicht', value: 'ca. 7,3 kg' },
    ],
    source: officialSource('Miele Nederland', 'https://www.miele.nl/product/12435960/sledestofzuiger-complete-c3-125-edition-mangorood'),
  },
  {
    id: 'curated:philips-hue-starterkit',
    slug: 'philips-hue-starterkit',
    title: 'Philips Hue White & Color Ambiance Starterkit 3× E27',
    brand: 'Philips Hue',
    gtin: '8719514291515',
    description: 'Een startset voor slimme kleurenverlichting met drie E27-lampen en Hue Bridge. Controleer bij aankoop altijd of dezelfde setinhoud wordt aangeboden.',
    categoryId: 'category:wonen-huishouden',
    visualKind: 'smart-lighting',
    specifications: [
      { label: 'Lampen', value: '3× E27 White & Color Ambiance' },
      { label: 'Lichtopbrengst', value: 'tot 1055 lumen per lamp' },
      { label: 'Kleurtemperatuur', value: '2000–6500 K' },
      { label: 'Bridge', value: 'Hue Bridge inbegrepen' },
      { label: 'Nominale levensduur', value: '25.000 uur' },
    ],
    source: officialSource('Philips Hue Nederland', 'https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-starterkit-3-e27-slimme-lampen-1100/8719514291515'),
  },
  {
    id: 'curated:bosch-serie-6-wasmachine',
    slug: 'bosch-serie-6-wasmachine',
    title: 'Bosch Serie 6 WGG244ZANL wasmachine',
    brand: 'Bosch',
    mpn: 'WGG244ZANL',
    description: 'Een Serie 6 voorlader met 9 kg vulgewicht. Door de exacte modelcode te tonen voorkomen we dat specificaties van andere Serie 6-uitvoeringen worden gemengd.',
    categoryId: 'category:wonen-huishouden',
    visualKind: 'washing-machine',
    specifications: [
      { label: 'Vulgewicht', value: '9 kg' },
      { label: 'Centrifugeren', value: 'max. 1400 rpm' },
      { label: 'Afmetingen', value: '845 × 598 × 588 mm' },
      { label: 'Type', value: 'Voorlader' },
      { label: 'Bijvullen', value: 'Bijvulfunctie aanwezig' },
    ],
    source: officialSource('Bosch Home Nederland', 'https://www.bosch-home.nl/nl/product/WGG244ZANL'),
  },
  {
    id: 'curated:philips-airfryer-3000-series',
    slug: 'philips-airfryer-3000-series',
    title: 'Philips Airfryer 3000 Series NA332/00',
    brand: 'Philips',
    mpn: 'NA332/00',
    description: 'Een 7,2-liter Airfryer uit de 3000-serie. Deze catalogusvariant gebruikt modelcode NA332/00 zodat capaciteit en functies eenduidig blijven.',
    categoryId: 'category:keuken-koffie',
    visualKind: 'airfryer',
    specifications: [
      { label: 'Capaciteit', value: '7,2 l' },
      { label: 'Vermogen', value: '2000 W' },
      { label: 'Kookfuncties', value: '16 functies' },
      { label: 'Technologie', value: 'RapidAir Plus' },
      { label: 'Afmetingen', value: '453 × 333 × 303,5 mm' },
    ],
    source: officialSource('Philips Nederland', 'https://www.philips.nl/c-p/NA332_00/3000-serie-airfryer-72l'),
  },
  {
    id: 'curated:delonghi-magnifica-start',
    slug: 'delonghi-magnifica-start',
    title: 'De’Longhi Magnifica Start ECAM220.20.W',
    brand: 'De’Longhi',
    mpn: 'ECAM220.20.W',
    description: 'Een volautomatische koffiemachine met handmatige melkopschuimer. Deze variant heeft vier direct selecteerbare warme functies.',
    categoryId: 'category:keuken-koffie',
    visualKind: 'coffee-machine',
    specifications: [
      { label: 'Waterreservoir', value: '1,8 l' },
      { label: 'Bonenreservoir', value: '250 g' },
      { label: 'Pompdruk', value: '15 bar' },
      { label: 'Directe functies', value: '4' },
      { label: 'Afmetingen', value: '240 × 440 × 350 mm' },
    ],
    source: officialSource('De’Longhi Nederland', 'https://www.delonghi.com/nl-nl/magnifica-start-automatische-koffiemachine-ecam220-20-w/p/ECAM220.20.W'),
  },
  {
    id: 'curated:ninja-foodi-max-dual-zone',
    slug: 'ninja-foodi-max-dual-zone',
    title: 'Ninja Foodi MAX Dual Zone AF400-serie',
    brand: 'Ninja',
    mpn: 'AF400',
    description: 'Een dual-zone airfryer met twee onafhankelijke lades. Modelcodes en bedieningslabels kunnen per Europese marktvariant verschillen.',
    categoryId: 'category:keuken-koffie',
    visualKind: 'dual-airfryer',
    specifications: [
      { label: 'Totale capaciteit', value: '9,5 l' },
      { label: 'Lades', value: '2× 4,75 l' },
      { label: 'Kookfuncties', value: '6' },
      { label: 'Vermogen AF400UK', value: '2470 W' },
      { label: 'Afmetingen AF400UK', value: '32,5 × 41,5 × 27 cm' },
    ],
    source: officialSource('Ninja Kitchen', 'https://ninjakitchen.co.uk/product/ninja-foodi-max-dual-zone-air-fryer-af400uk-zidAF400UK'),
  },
  {
    id: 'curated:kitchenaid-artisan',
    slug: 'kitchenaid-artisan',
    title: 'KitchenAid Artisan 5KSM175PS keukenmachine',
    brand: 'KitchenAid',
    mpn: '5KSM175PS',
    description: 'Een Artisan-keukenmachine met kantelbare kop. Deze variant wordt geleverd met een hoofdkom van 4,7 liter en een extra kom van 3 liter.',
    categoryId: 'category:keuken-koffie',
    visualKind: 'stand-mixer',
    specifications: [
      { label: 'Hoofdkom', value: '4,7 l' },
      { label: 'Extra kom', value: '3 l' },
      { label: 'Kop', value: 'Kantelbare kop' },
      { label: 'Aandrijving', value: 'Directe aandrijving' },
    ],
    source: officialSource('KitchenAid Nederland', 'https://www.kitchenaid.nl/keukenrobots/medium/859702301030/keukenrobot-met-kantelbare-kop-4-7l-artisan-5ksm175ps-steenkoolzwart'),
  },
  {
    id: 'curated:oral-b-io-6',
    slug: 'oral-b-io-6',
    title: 'Oral-B iO Series 6',
    brand: 'Oral-B',
    mpn: 'iO Series 6',
    description: 'Een elektrische tandenborstel met vijf poetsstanden, druksensor en display. Appfuncties vereisen een compatibele smartphone.',
    categoryId: 'category:persoonlijke-verzorging',
    visualKind: 'toothbrush',
    specifications: [
      { label: 'Poetsstanden', value: '5' },
      { label: 'Druksensor', value: 'Slimme druksensor' },
      { label: 'Timer', value: '2 minuten' },
      { label: 'Display', value: 'Interactief display' },
      { label: 'Connectiviteit', value: 'App-ondersteuning via Bluetooth' },
    ],
    source: officialSource('Oral-B Nederland', 'https://www.oralb.nl/nl-nl/product-collections/io-series-6-electric-toothbrush'),
  },
  {
    id: 'curated:philips-shaver-series-5000',
    slug: 'philips-shaver-series-5000',
    title: 'Philips Shaver Series 5000 S5898/35',
    brand: 'Philips',
    mpn: 'S5898/35',
    description: 'Een Wet & Dry-scheerapparaat uit de Series 5000. Door model S5898/35 te gebruiken blijven accuduur en meegeleverde accessoires controleerbaar.',
    categoryId: 'category:persoonlijke-verzorging',
    visualKind: 'shaver',
    specifications: [
      { label: 'Gebruik', value: 'Wet & Dry' },
      { label: 'Accuduur', value: '60 minuten' },
      { label: 'Oplaadtijd', value: '1 uur' },
      { label: 'Snelladen', value: '5 minuten voor één scheerbeurt' },
      { label: 'Scheersysteem', value: 'SteelPrecision · 360-D-koppen' },
    ],
    source: officialSource('Philips Nederland', 'https://www.philips.nl/c-p/S5898_35/shaver-series-5000-wet-dry-elektrisch-scheerapparaat'),
  },
  {
    id: 'curated:braun-silk-epil-9',
    slug: 'braun-silk-epil-9',
    title: 'Braun Silk-épil 9 9-011',
    brand: 'Braun',
    mpn: '9-011',
    description: 'Een Wet & Dry-epilator met brede flexibele kop en 40 MicroGrip-pincetten. Accessoiresetten verschillen per Silk-épil 9-variant.',
    categoryId: 'category:persoonlijke-verzorging',
    visualKind: 'epilator',
    specifications: [
      { label: 'Pincetten', value: '40 MicroGrip-pincetten' },
      { label: 'Gebruik', value: 'Wet & Dry' },
      { label: 'Gewicht', value: '179 g' },
      { label: 'Afmetingen', value: '163 × 65 × 45 mm' },
      { label: 'Batterij', value: 'Li-ion' },
    ],
    source: officialSource('Braun Nederland', 'https://www.braun.nl/nl-nl/female-hair-removal/epilators/silk-epil-9/silk-epil-9-9-011'),
  },
  {
    id: 'curated:philips-sonicare-6100',
    slug: 'philips-sonicare-6100',
    title: 'Philips Sonicare Series 6100 HX7400/01',
    brand: 'Philips Sonicare',
    mpn: 'HX7400/01',
    description: 'Een sonische elektrische tandenborstel met visuele druksensor. Deze HX7400/01-uitvoering heeft twee poetsstanden en drie intensiteitsniveaus.',
    categoryId: 'category:persoonlijke-verzorging',
    visualKind: 'toothbrush',
    specifications: [
      { label: 'Poetsstanden', value: '2 · Clean en Sensitive' },
      { label: 'Intensiteiten', value: '3 niveaus' },
      { label: 'Druksensor', value: 'Visuele druksensor' },
      { label: 'Timer', value: '2 minuten' },
      { label: 'Accuduur', value: 'tot 21 dagen' },
    ],
    source: officialSource('Philips Sonicare Nederland', 'https://www.philips.nl/c-p/HX7400_01/sonicare-rechargeable-toothbrush'),
  },
  {
    id: 'curated:garmin-forerunner-165',
    slug: 'garmin-forerunner-165',
    title: 'Garmin Forerunner 165',
    brand: 'Garmin',
    mpn: 'Forerunner 165',
    description: 'Een hardloophorloge met AMOLED-scherm, touchscreen en ingebouwde GPS. De Music-uitvoering heeft aanvullende muziekfuncties en is een aparte variant.',
    categoryId: 'category:sport-outdoor',
    visualKind: 'watch',
    specifications: [
      { label: 'Display', value: '1,2-inch AMOLED · 390 × 390' },
      { label: 'Gewicht', value: '39 g' },
      { label: 'Waterbestendigheid', value: '5 ATM' },
      { label: 'Smartwatch-accuduur', value: 'tot 11 dagen' },
      { label: 'GPS-accuduur', value: 'tot 19 uur' },
    ],
    source: officialSource('Garmin Nederland', 'https://www.garmin.com/nl-NL/compare/?compareProduct=1055469'),
  },
  {
    id: 'curated:fitbit-charge-6',
    slug: 'fitbit-charge-6',
    title: 'Fitbit Charge 6',
    brand: 'Fitbit',
    mpn: 'Charge 6',
    description: 'Een compacte fitnesstracker met ingebouwde GPS en Google-functies. Sommige inzichten en trainingen kunnen afhankelijk zijn van een abonnement of gekoppelde telefoon.',
    categoryId: 'category:sport-outdoor',
    visualKind: 'fitness-band',
    specifications: [
      { label: 'Accuduur', value: 'tot 7 dagen' },
      { label: 'Waterbestendigheid', value: 'tot 50 m' },
      { label: 'GPS', value: 'Ingebouwde GPS' },
      { label: 'Gewicht', value: '30 g met bandje' },
      { label: 'Afmetingen', value: '36,73 × 23,09 × 11,20 mm' },
    ],
    source: officialSource('Google Store / Fitbit', 'https://store.google.com/nl/product/fitbit_charge_6?hl=nl'),
  },
  {
    id: 'curated:thermos-stainless-king',
    slug: 'thermos-stainless-king',
    title: 'Thermos Stainless King Beverage Bottle 0,47 l (16 oz)',
    brand: 'Thermos',
    mpn: 'Stainless King 16oz Beverage Bottle',
    description: 'Een roestvrijstalen isoleerfles uit de Stainless King-serie. De 16 oz-uitvoering heeft een inhoud van ongeveer 0,47 liter.',
    categoryId: 'category:sport-outdoor',
    visualKind: 'bottle',
    specifications: [
      { label: 'Inhoud', value: '16 oz · ca. 0,47 l' },
      { label: 'Serie', value: 'Stainless King' },
      { label: 'Type', value: 'Beverage Bottle' },
      { label: 'Materiaal', value: 'Roestvrij staal' },
    ],
    source: officialSource('Thermos', 'https://thermos.com/collections/stainless-king-collection-2/size_16oz'),
  },
  {
    id: 'curated:coleman-octagon-8',
    slug: 'coleman-octagon-8',
    title: 'Coleman Octagon 8 Grey',
    brand: 'Coleman',
    mpn: '2176828',
    description: 'Een achtpersoons familietent met achthoekige leefruimte en scharnierende deur. Door de Grey-variant vast te leggen blijven gewicht en afmetingen eenduidig.',
    categoryId: 'category:sport-outdoor',
    visualKind: 'tent',
    specifications: [
      { label: 'Capaciteit', value: '8 personen' },
      { label: 'Oppervlak', value: '15,7 m²' },
      { label: 'Waterkolom', value: '2000 mm' },
      { label: 'Gewicht', value: '20,7 kg' },
      { label: 'Pakmaat', value: '85 × 30 × 30 cm' },
    ],
    source: officialSource('Coleman UK', 'https://www.colemanuk.co.uk/tents/tent-ranges/octagon/octagon-8-grey-tent/SAP_2176828.html'),
  },
  {
    id: 'curated:bosch-easymower-18v-32',
    slug: 'bosch-easymower-18v-32',
    title: 'Bosch EasyMower 18V-32-200',
    brand: 'Bosch',
    gtin: '4059952613802',
    mpn: '06008B9D00',
    description: 'Een compacte 18V-accumaaier voor kleinere gazons. Deze uitvoering wordt door Bosch als EasyMower 18V-32-200 gevoerd.',
    categoryId: 'category:tuin-klussen',
    visualKind: 'mower',
    specifications: [
      { label: 'Accuspanning', value: '18 V' },
      { label: 'Aanbevolen gazon', value: 'tot 200 m²' },
      { label: 'Maaibreedte', value: '32 cm' },
      { label: 'Maaihoogte', value: '20–60 mm · 3 standen' },
      { label: 'Opvangbak', value: '31 l' },
    ],
    source: officialSource('Bosch DIY', 'https://shop.bosch-diy.com/de/de/gartengeraete/535/easymower-18v-32-200-1-x-4-0-ah-akku-ladegeraet'),
  },
  {
    id: 'curated:karcher-k4-power-control',
    slug: 'karcher-k4-power-control',
    title: 'Kärcher K 4 Power Control',
    brand: 'Kärcher',
    mpn: '1.324-030.0',
    description: 'Een hogedrukreiniger voor schoonmaakklussen rond huis en tuin. De Power Control-uitvoering combineert instelbare druk met een watergekoelde motor.',
    categoryId: 'category:tuin-klussen',
    visualKind: 'pressure-washer',
    specifications: [
      { label: 'Werkdruk', value: '20–max. 130 bar' },
      { label: 'Wateropbrengst', value: 'max. 420 l/u' },
      { label: 'Vermogen', value: '1,8 kW' },
      { label: 'Hogedrukslang', value: '8 m' },
      { label: 'Gewicht zonder accessoires', value: '11,5 kg' },
    ],
    source: officialSource('Kärcher Nederland', 'https://www.kaercher.com/nl/outlet/produkten/k-4-power-control-13240300.html'),
  },
  {
    id: 'curated:makita-ddf484',
    slug: 'makita-ddf484',
    title: 'Makita DDF484Z',
    brand: 'Makita',
    mpn: 'DDF484Z',
    description: 'Een 18V LXT-accuboormachine met borstelloze motor. De Z-uitvoering wordt doorgaans als losse machine aangeboden; controleer altijd de winkelbundel voor accu, lader en koffer.',
    categoryId: 'category:tuin-klussen',
    visualKind: 'drill',
    specifications: [
      { label: 'Accuspanning', value: '18 V LXT' },
      { label: 'Max. koppel', value: '54 Nm' },
      { label: 'Toerental', value: '0–500 / 0–2000 rpm' },
      { label: 'Boorcapaciteit staal', value: '13 mm' },
      { label: 'Boorcapaciteit hout', value: '38 mm' },
    ],
    source: officialSource('Makita', 'https://makitauae.com/product/ddf484z-drill-driver-lxt/'),
  },
  {
    id: 'curated:gardena-sileno-minimo-500',
    slug: 'gardena-sileno-minimo-500',
    title: 'Gardena SILENO minimo 500',
    brand: 'Gardena',
    mpn: '15202-26',
    description: 'Een Bluetooth-robotmaaier voor gazons tot 500 m². De set bevat onder meer laadstation, grensdraad en krammen voor installatie.',
    categoryId: 'category:tuin-klussen',
    visualKind: 'robot-mower',
    specifications: [
      { label: 'Max. gazonoppervlak', value: '500 m²' },
      { label: 'Maaibreedte', value: '16 cm' },
      { label: 'Maaihoogte', value: '20–45 mm' },
      { label: 'Maaitijd per lading', value: '70 min' },
      { label: 'Geluidsniveau', value: '57 dB(A)' },
    ],
    source: officialSource('Gardena Nederland', 'https://www.gardena.com/nl/producten/gazononderhoud/robotmaaiers/robotmaaier-sileno-minimo-500-m/970462906.html'),
  },
]

export async function createCuratedCatalogRepository(): Promise<InMemoryCatalogRepository> {
  const repository = new InMemoryCatalogRepository({ categories: curatedCategories })
  for (const product of curatedProducts) await repository.upsertProduct(product)
  return repository
}
