import type { Category, Product } from '@/domain/catalog/types'
import { InMemoryCatalogRepository } from '@/infrastructure/catalog/in-memory-catalog-repository'

export const curatedCategories: Category[] = [
  { id: 'category:elektronica', slug: 'elektronica', name: 'Elektronica' },
  { id: 'category:wonen-huishouden', slug: 'wonen-huishouden', name: 'Wonen & huishouden' },
  { id: 'category:keuken-koffie', slug: 'keuken-koffie', name: 'Keuken & koffie' },
  { id: 'category:persoonlijke-verzorging', slug: 'persoonlijke-verzorging', name: 'Persoonlijke verzorging' },
  { id: 'category:sport-outdoor', slug: 'sport-outdoor', name: 'Sport & outdoor' },
  { id: 'category:tuin-klussen', slug: 'tuin-klussen', name: 'Tuin & klussen' },
]

export const curatedProducts: Product[] = [
  {
    id: 'curated:apple-macbook-air-13',
    slug: 'apple-macbook-air-13',
    title: 'Apple MacBook Air 13-inch',
    brand: 'Apple',
    description: 'Een compacte laptopfamilie voor studie, werk en dagelijks gebruik. Vergelijk vooral geheugen, opslag, aansluitingen en de uitvoering die bij jouw werkzaamheden past.',
    categoryId: 'category:elektronica',
  },
  {
    id: 'curated:sony-wh-1000xm6',
    slug: 'sony-wh-1000xm6',
    title: 'Sony WH-1000XM6',
    brand: 'Sony',
    description: 'Een draadloze over-ear hoofdtelefoon. Let bij je keuze op draagcomfort, ruisonderdrukking, microfoonkwaliteit, accuduur en compatibiliteit met je apparaten.',
    categoryId: 'category:elektronica',
  },
  {
    id: 'curated:samsung-galaxy-tab-s10-fe',
    slug: 'samsung-galaxy-tab-s10-fe',
    title: 'Samsung Galaxy Tab S10 FE',
    brand: 'Samsung',
    description: 'Een tablet voor media, studie en mobiel werken. Vergelijk schermformaat, opslag, accessoires, softwareondersteuning en de verbindingen die je nodig hebt.',
    categoryId: 'category:elektronica',
  },
  {
    id: 'curated:logitech-mx-master-3s',
    slug: 'logitech-mx-master-3s',
    title: 'Logitech MX Master 3S',
    brand: 'Logitech',
    description: 'Een draadloze muis voor productiviteit en langdurig bureauwerk. Let op pasvorm, knoppen, apparaatwissel, verbinding en compatibiliteit met je werkomgeving.',
    categoryId: 'category:elektronica',
  },
  {
    id: 'curated:dyson-v12-detect-slim',
    slug: 'dyson-v12-detect-slim',
    title: 'Dyson V12 Detect Slim',
    brand: 'Dyson',
    description: 'Een snoerloze steelstofzuiger voor regelmatig schoonmaken. Vergelijk gewicht, gebruiksduur, vloerzuigmonden, stofopvang en onderhoudskosten.',
    categoryId: 'category:wonen-huishouden',
  },
  {
    id: 'curated:miele-complete-c3',
    slug: 'miele-complete-c3',
    title: 'Miele Complete C3',
    brand: 'Miele',
    description: 'Een sledestofzuigerfamilie voor grondiger schoonmaakwerk. Let op de exacte uitvoering, vloerborstels, bereik, geluidsniveau en kosten van verbruiksartikelen.',
    categoryId: 'category:wonen-huishouden',
  },
  {
    id: 'curated:philips-hue-starterkit',
    slug: 'philips-hue-starterkit',
    title: 'Philips Hue Starterkit',
    brand: 'Philips Hue',
    description: 'Een startpunt voor slimme verlichting in huis. Controleer welke lampen, bridge, fitting, bediening en smart-homeplatforms in de gekozen set worden ondersteund.',
    categoryId: 'category:wonen-huishouden',
  },
  {
    id: 'curated:bosch-serie-6-wasmachine',
    slug: 'bosch-serie-6-wasmachine',
    title: 'Bosch Serie 6 wasmachine',
    brand: 'Bosch',
    description: 'Een wasmachinefamilie met meerdere uitvoeringen. Vergelijk capaciteit, afmetingen, energieverbruik, programma’s, geluidsniveau en de exacte modelcode.',
    categoryId: 'category:wonen-huishouden',
  },
  {
    id: 'curated:philips-airfryer-3000-series',
    slug: 'philips-airfryer-3000-series',
    title: 'Philips Airfryer 3000 Series',
    brand: 'Philips',
    description: 'Een heteluchtfriteusefamilie voor verschillende portiegroottes. Let op capaciteit, beschikbare programma’s, schoonmaakgemak en de ruimte die het apparaat inneemt.',
    categoryId: 'category:keuken-koffie',
  },
  {
    id: 'curated:delonghi-magnifica-start',
    slug: 'delonghi-magnifica-start',
    title: 'De’Longhi Magnifica Start',
    brand: 'De’Longhi',
    description: 'Een volautomatische koffiemachinefamilie. Vergelijk koffierecepten, melkbereiding, instelmogelijkheden, schoonmaakroutine en de kosten van onderhoud.',
    categoryId: 'category:keuken-koffie',
  },
  {
    id: 'curated:ninja-foodi-max-dual-zone',
    slug: 'ninja-foodi-max-dual-zone',
    title: 'Ninja Foodi MAX Dual Zone',
    brand: 'Ninja',
    description: 'Een airfryer met gescheiden bereidingszones. Kijk naar totale capaciteit, afmetingen, gelijktijdige programma’s en hoe eenvoudig manden en onderdelen schoon te maken zijn.',
    categoryId: 'category:keuken-koffie',
  },
  {
    id: 'curated:kitchenaid-artisan',
    slug: 'kitchenaid-artisan',
    title: 'KitchenAid Artisan keukenmachine',
    brand: 'KitchenAid',
    description: 'Een keukenmachinefamilie voor mengen, kloppen en kneden. Vergelijk kominhoud, meegeleverde accessoires, uitbreidingen, gewicht en beschikbare ruimte op het aanrecht.',
    categoryId: 'category:keuken-koffie',
  },
  {
    id: 'curated:oral-b-io-6',
    slug: 'oral-b-io-6',
    title: 'Oral-B iO 6',
    brand: 'Oral-B',
    description: 'Een elektrische tandenborstel. Vergelijk poetsstanden, feedbackfuncties, accugebruik, meegeleverde accessoires en de prijs van passende opzetborstels.',
    categoryId: 'category:persoonlijke-verzorging',
  },
  {
    id: 'curated:philips-shaver-series-5000',
    slug: 'philips-shaver-series-5000',
    title: 'Philips Shaver Series 5000',
    brand: 'Philips',
    description: 'Een serie elektrische scheerapparaten met meerdere uitvoeringen. Let op nat of droog gebruik, reiniging, accessoires, vervangonderdelen en de exacte modelvariant.',
    categoryId: 'category:persoonlijke-verzorging',
  },
  {
    id: 'curated:braun-silk-epil-9',
    slug: 'braun-silk-epil-9',
    title: 'Braun Silk-épil 9',
    brand: 'Braun',
    description: 'Een epilatorfamilie met verschillende accessoiresetten. Vergelijk toepassingsgebieden, nat of droog gebruik, accugebruik, onderhoud en meegeleverde opzetstukken.',
    categoryId: 'category:persoonlijke-verzorging',
  },
  {
    id: 'curated:philips-sonicare-6100',
    slug: 'philips-sonicare-6100',
    title: 'Philips Sonicare 6100',
    brand: 'Philips Sonicare',
    description: 'Een sonische elektrische tandenborstel. Let op poetsprogramma’s, drukfeedback, accugebruik, reisaccessoires en de beschikbaarheid van passende opzetborstels.',
    categoryId: 'category:persoonlijke-verzorging',
  },
  {
    id: 'curated:garmin-forerunner-165',
    slug: 'garmin-forerunner-165',
    title: 'Garmin Forerunner 165',
    brand: 'Garmin',
    description: 'Een sporthorloge gericht op hardlopen en dagelijkse activiteit. Vergelijk trainingsfuncties, kaart- en navigatiemogelijkheden, accugebruik en compatibiliteit met je telefoon.',
    categoryId: 'category:sport-outdoor',
  },
  {
    id: 'curated:fitbit-charge-6',
    slug: 'fitbit-charge-6',
    title: 'Fitbit Charge 6',
    brand: 'Fitbit',
    description: 'Een compacte activitytracker voor dagelijkse beweging en trainingen. Controleer welke metingen, abonnementsfuncties, telefoonkoppeling en accuduur voor jou relevant zijn.',
    categoryId: 'category:sport-outdoor',
  },
  {
    id: 'curated:thermos-stainless-king',
    slug: 'thermos-stainless-king',
    title: 'Thermos Stainless King isoleerfles',
    brand: 'Thermos',
    description: 'Een herbruikbare isoleerfles voor onderweg. Vergelijk inhoud, gewicht, drinkopening, lekbestendigheid, schoonmaakgemak en hoe lang je dranken warm of koud wilt houden.',
    categoryId: 'category:sport-outdoor',
  },
  {
    id: 'curated:coleman-octagon-8',
    slug: 'coleman-octagon-8',
    title: 'Coleman Octagon 8',
    brand: 'Coleman',
    description: 'Een ruime familietent. Let bij het vergelijken op slaapplaatsen, opzettijd, pakformaat, ventilatie, waterbestendigheid en hoeveel leefruimte je werkelijk nodig hebt.',
    categoryId: 'category:sport-outdoor',
  },
  {
    id: 'curated:bosch-easymower-18v-32',
    slug: 'bosch-easymower-18v-32',
    title: 'Bosch EasyMower 18V-32',
    brand: 'Bosch',
    description: 'Een compacte accumaaier voor kleinere gazons. Vergelijk maaibreedte, maaihoogtes, accuplattform, opvangbak, gewicht en wat er precies in de gekozen set zit.',
    categoryId: 'category:tuin-klussen',
  },
  {
    id: 'curated:karcher-k4-power-control',
    slug: 'karcher-k4-power-control',
    title: 'Kärcher K4 Power Control',
    brand: 'Kärcher',
    description: 'Een hogedrukreiniger voor verschillende schoonmaakklussen rond huis en tuin. Vergelijk drukregeling, slanglengte, accessoires, opslag en geschikte toepassingen.',
    categoryId: 'category:tuin-klussen',
  },
  {
    id: 'curated:makita-ddf484',
    slug: 'makita-ddf484',
    title: 'Makita DDF484',
    brand: 'Makita',
    description: 'Een accuboormachine voor uiteenlopende boor- en schroefklussen. Let op accuplattform, meegeleverde accu’s, koffer, gewicht en of de machine past bij je gebruik.',
    categoryId: 'category:tuin-klussen',
  },
  {
    id: 'curated:gardena-sileno-minimo-500',
    slug: 'gardena-sileno-minimo-500',
    title: 'Gardena SILENO minimo 500',
    brand: 'Gardena',
    description: 'Een robotmaaier voor kleinere gazons. Vergelijk aanbevolen gazonoppervlak, installatie, begrenzing, hellingen, bediening, onderhoud en winteropslag.',
    categoryId: 'category:tuin-klussen',
  },
]

export async function createCuratedCatalogRepository(): Promise<InMemoryCatalogRepository> {
  const repository = new InMemoryCatalogRepository({ categories: curatedCategories })
  for (const product of curatedProducts) await repository.upsertProduct(product)
  return repository
}
