import type { RecoveryActionState } from '@/app/intern/operations/recovery-actions'
import type { OperationsDashboard, OperationsIncidentSeverity } from '@/application/affiliate/operations-dashboard'
import { operatorCan, type OperatorRole } from '@/application/auth/operator-authorization'
import { relevantActionsForIncident, type OperatorActionHistoryFilters } from '@/application/operations/operator-action-context'
import type { OperatorActionHistoryItem } from '@/application/operations/operator-action-history'
import type { FeedOperationalTimeline } from '@/application/operations/feed-operational-timeline'
import { RecoveryActionForm } from '@/components/internal/recovery-action-form'

const severityLabel: Record<OperationsIncidentSeverity, string> = { critical: 'Kritiek', high: 'Hoog', medium: 'Middel', low: 'Laag' }
const severityClass: Record<OperationsIncidentSeverity, string> = { critical: 'border-red-200 bg-red-50 text-red-800', high: 'border-orange-200 bg-orange-50 text-orange-800', medium: 'border-amber-200 bg-amber-50 text-amber-800', low: 'border-slate-200 bg-slate-50 text-slate-700' }
const roleLabel: Record<OperatorRole, string> = { owner: 'Owner', operator: 'Operator', read_only: 'Read-only' }
const actionLabel: Record<string, string> = { 'feed.retry': 'Retry feed', 'feed.pause': 'Pauzeer feed', 'feed.resume': 'Hervat feed' }
type RecoveryAction = (previous: RecoveryActionState, formData: FormData) => Promise<RecoveryActionState>

export function InternalOperationsDashboard({ dashboard, actionHistory, fullActionHistory, feedTimelines, historyFilters, operatorEmail, operatorRole, signOutAction, retryFeedAction, pauseFeedAction, resumeFeedAction }: {
  dashboard: OperationsDashboard
  actionHistory: OperatorActionHistoryItem[]
  fullActionHistory: OperatorActionHistoryItem[]
  feedTimelines: FeedOperationalTimeline[]
  historyFilters: OperatorActionHistoryFilters
  operatorEmail: string
  operatorRole: OperatorRole
  signOutAction: () => Promise<void>
  retryFeedAction: RecoveryAction
  pauseFeedAction: RecoveryAction
  resumeFeedAction: RecoveryAction
}) {
  const canRetry = operatorCan(operatorRole, 'retry_feed')
  const canPause = operatorCan(operatorRole, 'pause_feed')
  const canResume = operatorCan(operatorRole, 'resume_feed')
  const timelineByFeed = new Map(feedTimelines.map((timeline) => [`${timeline.merchantId}:${timeline.sourceKey}`, timeline]))

  return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-10">
    <header className="flex flex-col gap-4 border-b border-slate-800 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">Winkelnu internal operations</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Partner operations</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Incidenten, recovery, feedstatus en menselijke acties in één operationele context.</p></div><div className="flex flex-col items-start gap-3 text-xs text-slate-500 sm:items-end"><span>Snapshot: {new Date(dashboard.generatedAt).toLocaleString('nl-NL')}</span><span>Ingelogd als {operatorEmail}</span><span className="rounded-full border border-slate-700 px-2.5 py-1 font-semibold text-slate-300">Rol: {roleLabel[operatorRole]}</span><form action={signOutAction}><button type="submit" className="rounded-lg border border-slate-700 px-3 py-2 font-semibold text-slate-300">Uitloggen</button></form></div></header>
    <section className="grid gap-3 py-8 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Integraties" value={dashboard.totals.integrations}/><Metric label="Actief" value={dashboard.totals.activeIntegrations}/><Metric label="Feeds" value={dashboard.totals.feeds}/><Metric label="Incidenten" value={dashboard.totals.incidents}/><Metric label="Kritiek + hoog" value={dashboard.totals.critical + dashboard.totals.high} emphasize/></section>
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_400px]"><section><div className="mb-4"><h2 className="text-lg font-semibold">Aandachtspunten</h2><p className="mt-1 text-sm text-slate-500">Per feed zie je nu ook de operationele tijdlijn.</p></div>
      {dashboard.incidents.length === 0 ? <div className="rounded-2xl border border-emerald-900/60 bg-emerald-950/30 p-6 text-sm text-emerald-200">Geen operationele incidenten in deze snapshot.</div> : <div className="space-y-3">{dashboard.incidents.map((incident) => {
        const relatedActions = relevantActionsForIncident(fullActionHistory, incident, 3)
        const timeline = incident.sourceKey ? timelineByFeed.get(`${incident.merchantId}:${incident.sourceKey}`) : undefined
        return <article key={incident.id} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${severityClass[incident.severity]}`}>{severityLabel[incident.severity]}</span><span className="text-xs text-slate-500">{incident.kind}</span>{incident.sourceKey ? <span className="text-xs text-slate-500">Feed: {incident.sourceKey}</span> : null}</div><h3 className="mt-3 text-base font-semibold text-white">{incident.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{incident.detail}</p><dl className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><div><dt className="inline">Merchant: </dt><dd className="inline text-slate-300">{incident.merchantName}</dd></div><div><dt className="inline">Integration: </dt><dd className="inline text-slate-300">{incident.integrationId}</dd></div></dl>{timeline ? <Timeline timeline={timeline}/> : relatedActions.length > 0 ? <div className="mt-4 text-xs text-slate-500">{relatedActions.length} recente recoveryacties beschikbaar.</div> : null}</div>
        <div className="w-full shrink-0 rounded-xl border border-slate-800 bg-slate-950/60 p-4 lg:w-80"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Eerstvolgende actie</p><p className="mt-2 text-sm leading-6 text-slate-300">{incident.operatorAction}</p>{incident.sourceKey ? <div className="mt-4 flex flex-wrap gap-3">{incident.kind === 'feed_paused' && canResume ? <RecoveryActionForm action={resumeFeedAction} merchantId={incident.merchantId} sourceKey={incident.sourceKey} requestKey={`${dashboard.generatedAt}:${incident.id}:resume`} label="Hervatten"/> : null}{incident.kind !== 'feed_paused' && canRetry ? <RecoveryActionForm action={retryFeedAction} merchantId={incident.merchantId} sourceKey={incident.sourceKey} requestKey={`${dashboard.generatedAt}:${incident.id}:retry`} label="Retry nu"/> : null}{incident.kind !== 'feed_paused' && canPause ? <RecoveryActionForm action={pauseFeedAction} merchantId={incident.merchantId} sourceKey={incident.sourceKey} requestKey={`${dashboard.generatedAt}:${incident.id}:pause`} label="Pauzeren" subtle confirmMessage={`Weet je zeker dat je feed ${incident.sourceKey} wilt pauzeren? Automatische imports stoppen totdat je de feed hervat.`}/> : null}</div> : null}</div></div></article>
      })}</div>}
    </section>
    <section><div className="mb-4"><h2 className="text-lg font-semibold">Recente acties</h2><p className="mt-1 text-sm text-slate-500">Filter op actor, actie, outcome, merchant of feed.</p></div><form method="get" className="mb-4 grid gap-2 rounded-2xl border border-slate-800 bg-slate-900/70 p-4"><input name="actor" defaultValue={historyFilters.actor ?? ''} placeholder="Actor e-mail" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"/><select name="action" defaultValue={historyFilters.action ?? ''} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"><option value="">Alle acties</option><option value="feed.retry">Retry</option><option value="feed.pause">Pauzeren</option><option value="feed.resume">Hervatten</option></select><select name="outcome" defaultValue={historyFilters.outcome ?? ''} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"><option value="">Alle outcomes</option><option value="succeeded">Geslaagd</option><option value="failed">Mislukt</option></select><input name="merchant" defaultValue={historyFilters.merchantId ?? ''} placeholder="Merchant ID" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"/><input name="feed" defaultValue={historyFilters.sourceKey ?? ''} placeholder="Feed key" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"/><div className="flex gap-2"><button className="rounded-lg border border-cyan-800 px-3 py-2 text-xs">Filter</button><a href="/intern/operations" className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Wissen</a></div></form>
      {actionHistory.length === 0 ? <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 text-sm text-slate-400">Geen operatoracties gevonden.</div> : <div className="space-y-3">{actionHistory.map((item) => <article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold">{actionLabel[item.action] ?? item.action}</p><p className="mt-1 text-xs text-slate-500">{item.actorEmail} · {roleLabel[item.actorRole]}</p></div><OutcomeBadge outcome={item.outcome}/></div><div className="mt-3 text-xs text-slate-500">{item.merchantId ? `Merchant: ${item.merchantId} · ` : ''}{item.sourceKey ? `Feed: ${item.sourceKey} · ` : ''}{new Date(item.occurredAt).toLocaleString('nl-NL')}</div></article>)}</div>}
    </section></div>
  </div></main>
}

function Timeline({ timeline }: { timeline: FeedOperationalTimeline }) { return <div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/40 p-3"><div className="flex flex-wrap gap-2 text-[11px]"><span className="font-semibold uppercase tracking-wider text-slate-500">Operationele tijdlijn</span><span className="text-slate-500">{timeline.isActive ? 'actief' : 'gepauzeerd'}</span>{timeline.healthStatus ? <span className="text-slate-500">health: {timeline.healthStatus}</span> : null}<span className="text-slate-500">failures: {timeline.failureCount}</span>{timeline.hasActiveLease ? <span className="text-cyan-300">import actief</span> : null}</div><ol className="mt-3 space-y-2 border-l border-slate-800 pl-3">{timeline.events.map((event) => <li key={event.id} className="text-xs"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-slate-200">{event.label}</span>{event.outcome ? <OutcomeBadge outcome={event.outcome} compact/> : null}<time className="text-slate-600">{new Date(event.occurredAt).toLocaleString('nl-NL')}</time></div>{event.detail ? <p className="mt-1 text-slate-500">{event.detail}</p> : null}</li>)}</ol></div> }
function OutcomeBadge({ outcome, compact = false }: { outcome: OperatorActionHistoryItem['outcome']; compact?: boolean }) { return <span className={`rounded-full border px-2 py-1 font-semibold ${compact ? 'text-[10px]' : 'text-[11px]'} ${outcome === 'succeeded' ? 'border-emerald-900 text-emerald-300' : 'border-red-900 text-red-300'}`}>{outcome === 'succeeded' ? 'Geslaagd' : 'Mislukt'}</span> }
function Metric({ label, value, emphasize = false }: { label: string; value: number; emphasize?: boolean }) { return <div className={`rounded-2xl border p-5 ${emphasize ? 'border-orange-900/70 bg-orange-950/30' : 'border-slate-800 bg-slate-900/70'}`}><div className="text-2xl font-semibold tabular-nums">{value}</div><div className="mt-1 text-xs uppercase tracking-wider text-slate-500">{label}</div></div> }
